### ISSUE TITLE
Support paramstyle='format' for list-type parameters

### ISSUE THREAD

**Issue by laserson** [cloudera/impyla#138]
Raised in #137

**Comment by cathmonster** [comment]
it looks like I missed on documentation in sql.py

If a DBAPI2 object, only sqlite3 is supported.
    flavor: {'sqlite', 'mysql'}, default 'sqlite'
        The flavor of SQL to use. Ignored when using SQLAlchemy engine.
        'mysql' is deprecated and will be removed in future versions, but it
        will be further supported through SQLAlchemy engines.
    schema : string, default None

So possibly sqlalchemy engine ...

**Comment by laserson** [comment]
Eitherway, just pushed a commit that supports the `format` paramstyle.  This might work now if you try the latest `master` of impyla.

**Comment by cathmonster** [comment]
Much appreciated,
It works! but we will test with sqlalchemy too...
Thanks much ...
