### ISSUE TITLE
would it be possible to have it in wheel format on pypi ?

### ISSUE THREAD

**Issue by stonebig** [cloudera/impyla#143]
.egg package format is supposed to be superseded by `wheel` package format, nowodays

**Comment by laserson** [comment]
I'll look into doing this at the next release.  Thanks for bringing it up!

**Comment by cjsavage** [comment]
is this still being explored?

**Comment by mariusvniekerk** [comment]
probably the easiest these days is to use conda-forge

**Comment by stonebig** [comment]
are there wheels on conda-forge ?

**Comment by wesm** [comment]
There are conda packages. If you would like wheels (and I don't understand why you need them for Impyla — this is a pure Python project) please submit a pull request.

**Comment by stonebig** [comment]
ok. request dropped: there is a wheel at cgohle's shop.
