### ISSUE TITLE
execute_async doesn't seem to be async

### ISSUE THREAD

**Issue by Raynes** [cloudera/impyla#157]
```python
args = parser.parse_args()

conn = connect(
    host=args.host,
    port=args.port,
    user=args.user,
    auth_mechanism="PLAIN"
)
cursor = conn.cursor()
cursor.execute_async("SELECT max(somecolumn) from sometable")

print("after execute")

while cursor.is_executing():
    print(cursor.get_log())
    print(cursor.get_summary())
    time.sleep(5)
```

When I run the above, nothing after the execute call happens until the query completes.

I assumed for a while that it was human error but this is straightforward enough that I can't see anything wrong with what I'm trying to do, as it's effectively the example provided with the pull request that added this feature. Can someone confirm this is actually a bug or if I'm insane? Running on Python 3.5.0

**Comment by Raynes** [comment]
Additionally, this is connecting to Hive, not Impala. Hive version is 1.1.0. Also of note is that if I do let the `get_log` and `get_summary` methods run, I get the following errors:

```
thrift.Thrift.TApplicationException: Invalid method name: 'GetExecSummary'
```

and for get_log

```
thriftpy.thrift.TApplicationException: Invalid method name: 'GetLog'
```

**Comment by laserson** [comment]
Thanks for reporting this, @Raynes.  The Impala HS2 impl always runs asynchronously, and so ignores the flag completely.

https://github.com/cloudera/Impala/blob/33ac44493fd3d24277d752f6bfb83175d310d5c7/be/src/service/impala-hs2-server.cc#L714-L716

@lskuff Do you think it is safe to set `runAsync` to true always.  Will Hive block if we try to fetch rows before they're ready?

**Comment by FlorianWilhelm** [comment]
@Raynes I am running into the same ``Invalid method name: 'GetLog'`` problem as you did. Did you find a way to use impyla in order to get logs from Hive? Or did you have to program it yourself with the help of thriftpy?

**Comment by ssubhasis** [comment]
i know its a old thread but i am getting the same error when i call get_summary, get_log and rowcounts. It says the methods are Invalid.
