### ISSUE TITLE
executemany method issue

### ISSUE THREAD

**Issue by msuluhan** [cloudera/impyla#163]
Hello 

Does impyla support executemany function ?

I am working in following environment
--> RHEL 6.6 -  2.6.32-504.el6.x86_64
--> python-2.6.6-52.el6.x86_64
--> impala-2.2.0+cdh5.4.5+0-1.cdh5.4.5.p0.8.el6.x86_64
--> impyla client downloaded at Nov 11

I have to import lots of data from various data sources into impala, so looks like impyla is good but inserting rows record by record with cursor.execute function is extremely slow for my business. So I am trying to insert with executemany function but I am getting following error or very similar variants of it in all attempts

impala.error.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 5 or more, and there are 5 supplied.

I found lots of issue about generic sql usage (mysql, pgsql, sqlite) regarding to python and tried many advices but no progress 

If impyla supports executemany could you help me about it ? 

Thanks
Murat

**Comment by mariusvniekerk** [comment]
I would advise that you rather load your data with ibis.  That supports much faster creation of external tablea

**Comment by laserson** [comment]
I agree with @mariusvniekerk.  Inserting lots of data through individual `INSERT` statements is a bad idea.  I think it might even create a separate file for each insert.  It'd be better to bulk load the data into HDFS and then register the table with a `CREATE EXTERNAL TABLE` statement.  I will close this issue for now.

That said, impyla should support `executemany`, so if there is actually a bug in that function, please open a new issue with more details about your query and the parameters you're supplying.
