### ISSUE TITLE
TProtocolException when trying to connect to Hive with Python 3 & impyla

### ISSUE THREAD

**Issue by mikeengland** [cloudera/impyla#165]
Impyla fails when trying to connect to Hive with Python 3 (on Mac OS X El Capitan):

Test code:

from impala.dbapi import connect
conn = connect(host='hiveserverhost.x.com', port=10000)
cursor = conn.cursor()
cursor.execute('show databases')
print(cursor.description) # prints the result set's schema
results = cursor.fetchall()
print(results)

See stacktrace:

Traceback (most recent call last):
  File "/Users/mike/projects/impyla_test/connect.py", line 3, in <module>
    cursor = conn.cursor()
  File "/Users/mike/analytics/venv/lib/python3.4/site-packages/impala/hiveserver2.py", line 88, in cursor
    session = self.service.open_session(user, configuration)
  File "/Users/mike/analytics/venv/lib/python3.4/site-packages/impala/hiveserver2.py", line 798, in open_session
    resp = self._rpc('OpenSession', req)
  File "/Users/mike/analytics/venv/lib/python3.4/site-packages/impala/hiveserver2.py", line 724, in _rpc
    response = self._execute(func_name, request)
  File "/Users/mike/analytics/venv/lib/python3.4/site-packages/impala/hiveserver2.py", line 741, in _execute
    return func(request)
  File "/Users/mike/analytics/venv/lib/python3.4/site-packages/thriftpy/thrift.py", line 159, in _req
    return self._recv(_api)
  File "/Users/mike/analytics/venv/lib/python3.4/site-packages/thriftpy/thrift.py", line 171, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "/Users/mike/analytics/venv/lib/python3.4/site-packages/thriftpy/protocol/binary.py", line 364, in read_message_begin
    self.trans, strict=self.strict_read)
  File "/Users/mike/analytics/venv/lib/python3.4/site-packages/thriftpy/protocol/binary.py", line 178, in read_message_begin
    message='No protocol version header')
thriftpy.protocol.exc.TProtocolException: TProtocolException(type=4)

**Comment by laserson** [comment]
Can you try adding `auth_mechanism='PLAIN'` to the call to connect?

**Comment by mikeengland** [comment]
Hi @laserson. Thanks, however this results in the error:

**Comment by laserson** [comment]
Yeah, for Python 3, you need to install the cython branch of the python-sasl repo:
https://github.com/cloudera/python-sasl/tree/cython

@wesm is working on getting this merged in, as Python 3 compatibility is definitely important to us.

**Comment by laserson** [comment]
Note, you can just run:

```
pip install git+https://github.com/laserson/python-sasl.git@cython
```

**Comment by mikeengland** [comment]
@laserson that worked for me! Appreciate your help.

**Comment by julienbaley** [comment]
@laserson : I know the ticket is closed, but do you know if there is any time scale for this to happen without having to manually install sasl@cython ?

**Comment by wesm** [comment]
@toddlipcon can you make me owner of https://pypi.python.org/pypi/sasl on PyPI? I can take over this project and make a release.

**Comment by wesm** [comment]
@julienbaley `pip install sasl` now installs the right thing . I will cut an impyla release sometime in the next week or so requiring this version. Let me know if you have any problems.

**Comment by julienbaley** [comment]
I will try that on Monday morning and will let you know.
It comes just at the right time, thanks :)

**Comment by julienbaley** [comment]
@wesm : Does that mean the `setup.py` should be updated (it still points to thrift_sasl) ?

(seems to work when I do a manual install of sasl)

**Comment by wesm** [comment]
@julienbaley `thrift_sasl` is something else: https://github.com/cloudera/thrift_sasl . I need to update the documentation for that package.

**Comment by wesm** [comment]
I just bumped the thrift_sasl version and added an explicit `sasl>=0.2.1` requirement to Impyla 0.13.2 (just released). Some other lingering issues I'm looking into

**Comment by rbhatia6** [comment]
I have the following 2 lines of code. I am using Anaconda on MacOS:

from impala.dbapi import connect
imp_conn = connect(host='hostname.corp.XXX.net', port=10000, user='XXX', password='XXX', auth_mechanism='PLAIN')

However, I get the following error. Is it possible for you to help out?

File "//anaconda/lib/python3.5/site-packages/impala/dbapi.py", line 147, in connect
auth_mechanism=auth_mechanism)
File "//anaconda/lib/python3.5/site-packages/impala/hiveserver2.py", line 644, in connect
transport.open()
File "//anaconda/lib/python3.5/site-packages/thrift_sasl/init.py", line 83, in open
message=("Bad status: %d (%s)" % (status, payload)))
thriftpy.transport.TTransportException: TTransportException(type=1, message="Bad status: 3 (b'Unsupported mechanism type PLAIN')")

**Comment by yang0733** [comment]
I'm getting an error pip install sasl in my conda virtualenv. 
pip3 install git+https://github.com/laserson/python-sasl.git@cython

am i missing something here? 

Collecting git+https://github.com/laserson/python-sasl.git@cython
  Cloning https://github.com/laserson/python-sasl.git (to cython) to /tmp/pip-qvz5leq8-build
Unpacking objects:   1% (1/66)   
Unpacking objects:   3% (2/66)   
Unpacking objects:   4% (3/66)   
Unpacking objects:   6% (4/66)   
Unpacking objects:   7% (5/66)   
Unpacking objects:   9% (6/66)   
Unpacking objects:  10% (7/66)   
Unpacking objects:  12% (8/66)   
Unpacking objects:  13% (9/66)   
Unpacking objects:  15% (10/66)   
Unpacking objects:  16% (11/66)   
Unpacking objects:  18% (12/66)   
Unpacking objects:  19% (13/66)   
Unpacking objects:  21% (14/66)   
Unpacking objects:  22% (15/66)   
Unpacking objects:  24% (16/66)   
Unpacking objects:  25% (17/66)   
Unpacking objects:  27% (18/66)   
Unpacking objects:  28% (19/66)   
Unpacking objects:  30% (20/66)   
Unpacking objects:  31% (21/66)   
Unpacking objects:  33% (22/66)   
Unpacking objects:  34% (23/66)   
Unpacking objects:  36% (24/66)   
Unpacking objects:  37% (25/66)   
Unpacking objects:  39% (26/66)   
Unpacking objects:  40% (27/66)   
Unpacking objects:  42% (28/66)   
Unpacking objects:  43% (29/66)   
Unpacking objects:  45% (30/66)   
Unpacking objects:  46% (31/66)   
Unpacking objects:  48% (32/66)   
Unpacking objects:  50% (33/66)   
Unpacking objects:  51% (34/66)   
Unpacking objects:  53% (35/66)   
Unpacking objects:  54% (36/66)   
Unpacking objects:  56% (37/66)   
Unpacking objects:  57% (38/66)   
Unpacking objects:  59% (39/66)   
Unpacking objects:  60% (40/66)   
Unpacking objects:  62% (41/66)   
Unpacking objects:  63% (42/66)   
Unpacking objects:  65% (43/66)   
Unpacking objects:  66% (44/66)   
Unpacking objects:  68% (45/66)   
Unpacking objects:  69% (46/66)   
Unpacking objects:  71% (47/66)   
Unpacking objects:  72% (48/66)   
Unpacking objects:  74% (49/66)   
Unpacking objects:  75% (50/66)   
Unpacking objects:  77% (51/66)   
Unpacking objects:  78% (52/66)   
Unpacking objects:  80% (53/66)   
Unpacking objects:  81% (54/66)   
Unpacking objects:  83% (55/66)   
Unpacking objects:  84% (56/66)   
Unpacking objects:  86% (57/66)   
Unpacking objects:  87% (58/66)   
Unpacking objects:  89% (59/66)   
Unpacking objects:  90% (60/66)   
Unpacking objects:  92% (61/66)   
Unpacking objects:  93% (62/66)   
Unpacking objects:  95% (63/66)   
Unpacking objects:  96% (64/66)   
Unpacking objects:  98% (65/66)   
Unpacking objects: 100% (66/66)   
Unpacking objects: 100% (66/66), done.
Requirement already satisfied: six in ./.conda/envs/nanyan/lib/python3.5/site-packages (from sasl==0.2.0)
Installing collected packages: sasl
  Running setup.py install for sasl ... - \ | / error
    Complete output from command /users/nanyan/.conda/envs/nanyan/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-qvz5leq8-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pmjfqb50-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/sasl
    copying sasl/__init__.py -> build/lib.linux-x86_64-3.5/sasl
    running egg_info
    creating sasl.egg-info
    writing top-level names to sasl.egg-info/top_level.txt
    writing dependency_links to sasl.egg-info/dependency_links.txt
    writing sasl.egg-info/PKG-INFO
    writing requirements to sasl.egg-info/requires.txt
    writing manifest file 'sasl.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'sasl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'sasl.egg-info/SOURCES.txt'
    copying sasl/saslwrapper.cpp -> build/lib.linux-x86_64-3.5/sasl
    copying sasl/saslwrapper.h -> build/lib.linux-x86_64-3.5/sasl
    running build_ext
    building 'sasl.saslwrapper' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/sasl
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isasl -I/users/nanyan/.conda/envs/nanyan/include/python3.5m -c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-3.5/sasl/saslwrapper.o
    cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
    In file included from sasl/saslwrapper.cpp:254:
    sasl/saslwrapper.h:22:23: error: sasl/sasl.h: No such file or directory
    In file included from sasl/saslwrapper.cpp:254:
    sasl/saslwrapper.h:145: error: ‘sasl_interact_t’ has not been declared
    sasl/saslwrapper.h:148: error: ‘sasl_conn_t’ has not been declared
    sasl/saslwrapper.h:148: error: ‘sasl_secret_t’ has not been declared
    sasl/saslwrapper.h:151: error: ISO C++ forbids declaration of ‘sasl_conn_t’ with no type
    sasl/saslwrapper.h:151: error: expected ‘;’ before ‘*’ token
    sasl/saslwrapper.h:152: error: ‘sasl_callback_t’ does not name a type
    sasl/saslwrapper.h:165: error: ISO C++ forbids declaration of ‘sasl_secret_t’ with no type
    sasl/saslwrapper.h:165: error: expected ‘;’ before ‘*’ token
    sasl/saslwrapper.h: In constructor ‘saslwrapper::ClientImpl::ClientImpl()’:
    sasl/saslwrapper.h:35: error: class ‘saslwrapper::ClientImpl’ does not have any field named ‘conn’
    sasl/saslwrapper.h:35: error: class ‘saslwrapper::ClientImpl’ does not have any field named ‘secret’
    sasl/saslwrapper.h: In destructor ‘saslwrapper::ClientImpl::~ClientImpl()’:
    sasl/saslwrapper.h:36: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:36: error: ‘sasl_dispose’ was not declared in this scope
    sasl/saslwrapper.h:36: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘void saslwrapper::ClientImpl::lastCallback()’:
    sasl/saslwrapper.h:143: error: ‘SASL_CB_LIST_END’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘bool saslwrapper::ClientImpl::init()’:
    sasl/saslwrapper.h:179: error: ‘sasl_client_init’ was not declared in this scope
    sasl/saslwrapper.h:180: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h:181: error: ‘sasl_errstring’ was not declared in this scope
    sasl/saslwrapper.h:187: error: ‘SASL_CB_GETREALM’ was not declared in this scope
    sasl/saslwrapper.h:189: error: ‘SASL_CB_USER’ was not declared in this scope
    sasl/saslwrapper.h:190: error: ‘SASL_CB_AUTHNAME’ was not declared in this scope
    sasl/saslwrapper.h:193: error: ‘SASL_CB_PASS’ was not declared in this scope
    sasl/saslwrapper.h:195: error: ‘SASL_CB_PASS’ was not declared in this scope
    sasl/saslwrapper.h:203: error: ‘SASL_NEED_PROXY’ was not declared in this scope
    sasl/saslwrapper.h:205: error: ‘callbacks’ was not declared in this scope
    sasl/saslwrapper.h:205: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:205: error: ‘sasl_client_new’ was not declared in this scope
    sasl/saslwrapper.h:206: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h:207: error: ‘sasl_errstring’ was not declared in this scope
    sasl/saslwrapper.h:211: error: ‘sasl_security_properties_t’ was not declared in this scope
    sasl/saslwrapper.h:211: error: expected ‘;’ before ‘secprops’
    sasl/saslwrapper.h:213: error: ‘secprops’ was not declared in this scope
    sasl/saslwrapper.h:220: error: ‘SASL_SEC_PROPS’ was not declared in this scope
    sasl/saslwrapper.h:220: error: ‘sasl_setprop’ was not declared in this scope
    sasl/saslwrapper.h:221: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h:223: error: ‘sasl_dispose’ was not declared in this scope
    sasl/saslwrapper.h:229: error: ‘SASL_AUTH_EXTERNAL’ was not declared in this scope
    sasl/saslwrapper.h:230: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h:232: error: ‘sasl_dispose’ was not declared in this scope
    sasl/saslwrapper.h:237: error: ‘SASL_SSF_EXTERNAL’ was not declared in this scope
    sasl/saslwrapper.h:238: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h:240: error: ‘sasl_dispose’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘bool saslwrapper::ClientImpl::setAttr(const std::string&, const std::string&)’:
    sasl/saslwrapper.h:259: error: ‘secret’ was not declared in this scope
    sasl/saslwrapper.h:260: error: ‘sasl_secret_t’ was not declared in this scope
    sasl/saslwrapper.h:260: error: expected primary-expression before ‘)’ token
    sasl/saslwrapper.h:260: error: expected ‘;’ before ‘malloc’
    sasl/saslwrapper.h: In member function ‘bool saslwrapper::ClientImpl::start(const std::string&, std::string&, std::string&)’:
    sasl/saslwrapper.h:295: error: ‘sasl_interact_t’ was not declared in this scope
    sasl/saslwrapper.h:295: error: ‘prompt’ was not declared in this scope
    sasl/saslwrapper.h:301: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:301: error: ‘sasl_client_start’ was not declared in this scope
    sasl/saslwrapper.h:302: error: ‘SASL_INTERACT’ was not declared in this scope
    sasl/saslwrapper.h:304: error: ‘SASL_INTERACT’ was not declared in this scope
    sasl/saslwrapper.h:305: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h:305: error: ‘SASL_CONTINUE’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘bool saslwrapper::ClientImpl::step(const std::string&, std::string&)’:
    sasl/saslwrapper.h:318: error: ‘sasl_interact_t’ was not declared in this scope
    sasl/saslwrapper.h:318: error: ‘prompt’ was not declared in this scope
    sasl/saslwrapper.h:323: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:323: error: ‘sasl_client_step’ was not declared in this scope
    sasl/saslwrapper.h:324: error: ‘SASL_INTERACT’ was not declared in this scope
    sasl/saslwrapper.h:326: error: ‘SASL_INTERACT’ was not declared in this scope
    sasl/saslwrapper.h:327: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h:327: error: ‘SASL_CONTINUE’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘bool saslwrapper::ClientImpl::encode(const std::string&, std::string&)’:
    sasl/saslwrapper.h:340: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:340: error: ‘sasl_encode’ was not declared in this scope
    sasl/saslwrapper.h:341: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘bool saslwrapper::ClientImpl::decode(const std::string&, std::string&)’:
    sasl/saslwrapper.h:361: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:361: error: ‘sasl_decode’ was not declared in this scope
    sasl/saslwrapper.h:362: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘bool saslwrapper::ClientImpl::getUserId(std::string&)’:
    sasl/saslwrapper.h:378: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:378: error: ‘SASL_USERNAME’ was not declared in this scope
    sasl/saslwrapper.h:378: error: ‘sasl_getprop’ was not declared in this scope
    sasl/saslwrapper.h:379: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘bool saslwrapper::ClientImpl::getSSF(int*)’:
    sasl/saslwrapper.h:390: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:390: error: ‘SASL_SSF’ was not declared in this scope
    sasl/saslwrapper.h:390: error: ‘sasl_getprop’ was not declared in this scope
    sasl/saslwrapper.h:391: error: ‘SASL_OK’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘void saslwrapper::ClientImpl::addCallback(long unsigned int, void*)’:
    sasl/saslwrapper.h:407: error: ‘callbacks’ was not declared in this scope
    sasl/saslwrapper.h: In member function ‘void saslwrapper::ClientImpl::setError(const std::string&, int, const std::string&, const std::string&)’:
    sasl/saslwrapper.h:419: error: ‘conn’ was not declared in this scope
    sasl/saslwrapper.h:420: error: ‘sasl_errdetail’ was not declared in this scope
    sasl/saslwrapper.h:422: error: ‘sasl_errstring’ was not declared in this scope
    sasl/saslwrapper.h: At global scope:
    sasl/saslwrapper.h:434: error: variable or field ‘interact’ declared void
    sasl/saslwrapper.h:434: error: ‘sasl_interact_t’ was not declared in this scope
    sasl/saslwrapper.h:434: error: ‘prompt’ was not declared in this scope
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/users/nanyan/.conda/envs/nanyan/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-qvz5leq8-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pmjfqb50-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-qvz5leq8-build/
