### ISSUE TITLE
Failure to connect to cluster without error message

### ISSUE THREAD

**Issue by ispmarin** [cloudera/impyla#166]
I'm trying to use `impyla` to connect to a `hive` server:

    from impala.dbapi import connect
    conn = connect(host='localhost', port=11112)
    cursor = conn.cursor()

I locks up on the `conn.cursor()` line. No timeouts so far (1h+) and no connection or failure.

Not sure if related, but I can connect using `pyhive` and directly using `beeline`. Using `pyhive` I can do `show databases` but get an error when trying to do a `SELECT`. The `beeline` connection line is

```
beeline -u jdbc:hive2://localhost:11112 -n hive job.queue.name=myqueue
```
and everything works ok.

**Comment by Takayoshi-Aoyagi** [comment]
A similar probrem was encountered in my environment.

conn.cursor() did not return value forever. 

I can connect HiveServer2 via beeline. But, I CAN'T connect it via impyla.
So, HiveServer2 is alive.

I wonder it is an authentication problem.
What is proper option of auth_mechanism to set?
I want impyla to behave same as beeline.

RHEL 6.2
Hive 1.2.1.2.3.0.0-2557
Python 2.7.8,
impyla  0.12.0

**Comment by laserson** [comment]
Hive requires a SASL transport with the `PLAIN` mechanism.  Add `auth_mechanism='PLAIN'` in the call to `connect()` and that should solve this problem

**Comment by Takayoshi-Aoyagi** [comment]
Hi, laserson

I added auth_mechanism='PLAIN'
But another probrem happened.

--- error log ---
Connecting ...
Traceback (most recent call last):
  File "hive2_test.py", line 12, in <module>
    hive = Hive2(logger)
  File "/home/hdbadm18/aoyagi/hive_repair_table/lib/hive2.py", line 18, in __init__
    auth_mechanism='PLAIN'
  File "/home/hdbadm18/.pyenv/versions/2.7.8/lib/python2.7/site-packages/impala/dbapi.py", line 85, in connect
    auth_mechanism=auth_mechanism)
  File "/home/hdbadm18/.pyenv/versions/2.7.8/lib/python2.7/site-packages/impala/hiveserver2.py", line 568, in connect
    transport.open()
  File "/home/hdbadm18/.pyenv/versions/2.7.8/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 72, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found

**Comment by ispmarin** [comment]
In my case, passing 'PLAIN' to `auth_mechanism` worked.

**Comment by Takayoshi-Aoyagi** [comment]
Finally, I found the cause.
libsasl.so was bad in my environment.
Now it works well with PLAIN auth_mechanism.

Thank you

**Comment by laserson** [comment]
Great!  Feel free to open a new issue if there are more problems.

**Comment by rbhatia6** [comment]
I have the following 2 lines of code. I am using Anaconda on MacOS:

from impala.dbapi import connect
imp_conn = connect(host='hostname.corp.XXX.net', port=10000, user='XXX', password='XXX', auth_mechanism='PLAIN')

However, I get the following error. Is it possible for you to help out?

File "//anaconda/lib/python3.5/site-packages/impala/dbapi.py", line 147, in connect
auth_mechanism=auth_mechanism)
File "//anaconda/lib/python3.5/site-packages/impala/hiveserver2.py", line 644, in connect
transport.open()
File "//anaconda/lib/python3.5/site-packages/thrift_sasl/init.py", line 83, in open
message=("Bad status: %d (%s)" % (status, payload)))
thriftpy.transport.TTransportException: TTransportException(type=1, message="Bad status: 3 (b'Unsupported mechanism type PLAIN')")

**Comment by ZuluagaSD** [comment]
Hey @laserson I have the following code:

```python
import ibis

client = ibis.impala.connect(host='grid.company.corp',
                             port=21050,
                             auth_mechanism='PLAIN',
                             use_ssl=True,
                             kerberos_service_name='impala',
                             ca_cert='D:\Users\USER\Documents\cachain')
```

I tried changing the `auth_mechanism` but I still get the following error:

 `thrift.transport.TTransport.TTransportException: Hostname we connected to "grid.company.corp" doesn't match certificate provided commonName "server.company.corp"`

**Comment by laserson** [comment]
Looks like an issue with the security configuration more than anything.  But I'll also mention that I no longer maintain this code and don't have a way to test out any problems.

**Comment by krishnakt031990** [comment]
@ZuluagaSD  It is the problem with the load balancer. Where the load balancer is sending a cert of the machine which runs the impala d demon while you are trying to hit the load balancer. Does any one here have a work around for this??

**Comment by calloc** [comment]
@krishnakt031990 @ZuluagaSD does anyone has the workaround for Impala TLS via Load Balancer? 
Please help this is urgent....

**Comment by krishnakt031990** [comment]
Hello @calloc Yes there is a work around. The problem we are facing is due to the TLS package impyla is using. It tries to compare the name of the server you are hitting which I believe will be your load balancer  to the name passed back from the one of the machines in the response and invalidates it. The work around is to comment out that line of code which checks for this specific condition. rather what I did was make use of regex to see if they belong to the same domain/DNS entry points. Can you post the error to me so that I can point out the exact class also? It has been a while and I seem to forget the name of that class.

from impala.dbapi import connect
conn = connect(host='loadbalancer', port=21050, use_ssl=True, auth_mechanism='GSSAPI', ca_cert='cert', kerberos_service_name='impala')

These are the commands I havae used.

**Comment by calloc** [comment]
Hello, @krishnakt031990 

This is the error message below (ipython).

```
In [10]: conn = connect(host,port, **options)
---------------------------------------------------------------------------
TTransportException                       Traceback (most recent call last)
<ipython-input-10-4b0d9ca31aff> in <module>()
----> 1 conn = connect(host,port, **options)

/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/impyla-0.14.0-py2.7.egg/impala/dbapi.pyc in connect(host, port, database, timeout, use_ssl, ca_cert, auth_mechanism, user, password, kerberos_service_name, use_ldap, ldap_user, ldap_password, use_kerberos, protocol)
    145                           ca_cert=ca_cert, user=user, password=password,
    146                           kerberos_service_name=kerberos_service_name,
--> 147                           auth_mechanism=auth_mechanism)
    148     return hs2.HiveServer2Connection(service, default_db=database)
    149

/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/impyla-0.14.0-py2.7.egg/impala/hiveserver2.pyc in connect(host, port, timeout, use_ssl, ca_cert, user, password, kerberos_service_name, auth_mechanism)
    756     transport = get_transport(sock, host, kerberos_service_name,
    757                               auth_mechanism, user, password)
--> 758     transport.open()
    759     protocol = TBinaryProtocol(transport)
    760     if six.PY2:

/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/thrift_sasl-0.2.1-py2.7.egg/thrift_sasl/__init__.pyc in open(self)
     59   def open(self):
     60     if not is_open_compat(self._trans):
---> 61       self._trans.open()
     62
     63     if self.sasl is not None:

/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/thrift-1.0.0.dev0-py2.7-linux-x86_64.egg/thrift/transport/TSSLSocket.pyc in open(self)
    112                                 message=message)
    113     if self.validate:
--> 114       self._validate_cert()
    115
    116   def _validate_cert(self):

/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/thrift-1.0.0.dev0-py2.7-linux-x86_64.egg/thrift/transport/TSSLSocket.pyc in _validate_cert(self)
    149           type=TTransportException.UNKNOWN,
    150           message='Hostname we connected to "%s" doesn\'t match certificate '
--> 151                   'provided commonName "%s"' % (self.host, certhost))
    152     raise TTransportException(
    153       type=TTransportException.UNKNOWN,

TTransportException: Hostname we connected to "loadbalancer.example.com" doesn't match certificate provided commonName "impalad10.example.com"

In [11]: host
Out[11]: 'loadbalancer.example.com'

In [12]: port
Out[12]: 21050

In [13]: options
Out[13]:
{'auth_mechanism': 'GSSAPI',
 'ca_cert': '/path/to/cacert.pem',
 'kerberos_service_name': 'impala',
 'use_ssl': True}
```


Note that each of impalad's Certificate contains CN of its FQDN name and has two DNS names in SAN - its FQDN and Load Balancer FQDN

Thanks in advance for pointing out the solution.

**Comment by krishnakt031990** [comment]
Ok so you see the problem is with the /opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/thrift-1.0.0.dev0-py2.7-linux-x86_64.egg/thrift/transport/TSSLSocket.py package trying to validate that the names passed in were the same. Remove that condition and it should work as expected. There is no addition risk in terms of security in this case. So you can go ahead with it.

**Comment by calloc** [comment]
I see. Thank you for your kind help. :))

**Comment by ExpressGit** [comment]
@Takayoshi-Aoyagi  
 
       can you  tell us how to sovle this problem.

thanks

**Comment by Takayoshi-Aoyagi** [comment]
Hello, @ExpressGit 

I don't remember exactly, but I created a symbolik link.

$ cd /usr/lib64/
$ sudo ln -sf libsasl2.so.2.0.23 libsasl2.so.3

My environment is:

$ uname -a
Linux hdp236hdb 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Mar 10 17:01:00 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.5 (Santiago)
