### ISSUE TITLE
thriftpy 0.3.x TSocket.set_timeout is gone

### ISSUE THREAD

**Issue by wesm** [cloudera/impyla#167]
I'm developing primarily with Python 3.x now so I ran into this right away.

**Comment by laserson** [comment]
Looks like this changed a month ago?
https://github.com/eleme/thriftpy/commit/83a921a9b64f26da62704fd5c58fbb3a2a26249f

**Comment by lxyu** [comment]
add back in https://github.com/eleme/thriftpy/commit/70bfa0b04cb1a551025e1a1902c2fadc85a28705, sorry for the inconvenience.

**Comment by wesm** [comment]
@lxyu thank you

**Comment by laserson** [comment]
Moved to the new API in 35ce92af01c06f1c95910a37bd6d1d99f18b9fcd

**Comment by wesm** [comment]
Are these changes released in thriftpy?

**Comment by laserson** [comment]
Which changes?  The backwards compatibility fix in thriftpy does NOT appear to be in a release.  The new API for setting the timeout in thriftpy IS in the latest release, which is why the changes in 35ce92a fixed the build.

**Comment by wesm** [comment]
gotcha, thanks

**Comment by avram** [comment]
The changes however are not released in Impyla -- would be great to get a new release of Impyla, preferably one that pins the thriftpy dependency at 0.3.3 to keep this stable.
