### ISSUE TITLE
would like offer some help for thriftpy adoption

### ISSUE THREAD

**Issue by lxyu** [cloudera/impyla#168]
Hi, thriftpy author here. Just came across this repo and would like offer some help for thriftpy adoption.

After a glance of the source code, it seems the main issue is `SaslClient` part, which should be easy to support. What do you think about it?

**Comment by laserson** [comment]
I think that'd be great.  We've also disabled the Cython for the moment, but would be great to get it working as well.

**Comment by lxyu** [comment]
Glad to hear that. I was on Chinese new year vacation the last two weeks, working on it now.
