### ISSUE TITLE
thrifypy 0.3.3 breaks impala.dbapi.connect

### ISSUE THREAD

**Issue by tdhopper** [cloudera/impyla#173]
I am running Impyla 0.12.0 on Python 0.3.5. This code worked fine under thriftpy 0.3.2.

```
from impala.dbapi import connect

impala_host = "192.225.***.***"
impala_port = 21050

conn = connect(host=impala_host, port=impala_port) 
```

However, with the new thriftpy 0.3.3, I get 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-c56fc21002f4> in <module>()
      6 impala_port = 21050
      7 
----> 8 conn = connect(host=impala_host, port=impala_port)
      9 cursor = conn.cursor()

/Users/tdhopper/miniconda/envs/env/lib/python3.5/site-packages/impala/dbapi.py in connect(host, port, database, timeout, use_ssl, ca_cert, auth_mechanism, user, password, kerberos_service_name, use_ldap, ldap_user, ldap_password, use_kerberos, protocol)
     83                           ca_cert=ca_cert, user=user, password=password,
     84                           kerberos_service_name=kerberos_service_name,
---> 85                           auth_mechanism=auth_mechanism)
     86     return hs2.HiveServer2Connection(service, default_db=database)
     87 

/Users/tdhopper/miniconda/envs/env/lib/python3.5/site-packages/impala/hiveserver2.py in connect(host, port, timeout, use_ssl, ca_cert, user, password, kerberos_service_name, auth_mechanism)
    563         sock.setTimeout(timeout)
    564     elif six.PY3:
--> 565         sock.set_timeout(timeout)
    566     transport = get_transport(sock, host, kerberos_service_name,
    567                               auth_mechanism, user, password)

AttributeError: 'TSocket' object has no attribute 'set_timeout'
```

[The error is thrown here.](https://github.com/cloudera/impyla/blob/v0.12.0/impala/hiveserver2.py#L565)

[Here's the thriftpy diff between 0.3.2 and 0.3.3.](https://github.com/eleme/thriftpy/compare/v0.3.2...v0.3.3#diff-9410a0390cf977e773ddc99390f25d54L5) It looks like `set_timeout` [was removed](https://github.com/eleme/thriftpy/compare/eleme:324b65b...eleme:880695c#diff-d6eed6bea48705dc95323e7fc227744eL62) and the timeout is now [set in the constructor](https://github.com/eleme/thriftpy/commit/83a921a9b64f26da62704fd5c58fbb3a2a26249f#diff-d6eed6bea48705dc95323e7fc227744eR19). I may try to patch tomorrow.

**Comment by laserson** [comment]
This should hopefully be fixed soon.  Waiting for thriftpy to issue a release with a fix for the incompatibility.

**Comment by tdhopper** [comment]
Fix with [thriftpy 0.3.4](https://github.com/eleme/thriftpy/tree/v0.3.4)

**Comment by wesm** [comment]
this is still partially broken https://github.com/eleme/thriftpy/pull/183 tracking

**Comment by tdhopper** [comment]
I'm seeing `HiveServer2Error` errors thrown on large queries that appear to go away if I use 0.3.2. Possibly related?

**Comment by wesm** [comment]
What kind of HS2 errors? Do they seem somehow Thrift protocol related?

**Comment by laserson** [comment]
This might be fixed when thriftpy cuts a new release.  Currently, if you don't manually specify a timeout, then a very short default timeout is used for the Thrift connection, which may break on large queries.  One possible workaround would be to manually specify a large timeout.  When they cut a new release, then not specifying or specifying a timeout of `None` will mean "no timeout".

**Comment by tdhopper** [comment]
@wesm, yes. Thrown here: https://github.com/cloudera/impyla/blob/0413de76893aac9814979a660e47595320d760e5/impala/hiveserver2.py#L826

**Comment by lxyu** [comment]
should be fixed in v0.3.5.

**Comment by wesm** [comment]
@tdhopper can you verify if thriftpy 0.3.5 resolves your issue? I am going to do some more testing of #177 and then cut the 0.13.2 release.

**Comment by tdhopper** [comment]
I'm out of the office till Monday. Probably won't happen before then, sorry.

**Comment by wesm** [comment]
No worries, I'll wait!

**Comment by tdhopper** [comment]
@wesm Both errors mentioned above disappear with 0.3.5.
