### ISSUE TITLE
Dict cursor support for query result

### ISSUE THREAD

**Issue by xch91** [cloudera/impyla#192]
Hi, it turns out that our company's data scientists previously relied on MySQL to play around with data and used DictCursor quite extensively; now that we migrated the data to Hive and they would like to have as little change on the working reporting code as possible.

I am relatively new to the convention and standards of contributing to open source project but made this commit in my forked impyla: 09500f611868bbeb91cce55f9360204c14f861ee. Wondering if I should just submit a PR or should I add some other stuff to conform to the project standard :)

Thank you.

**Comment by julienbaley** [comment]
I think dict comprehension is a python >=2.7 feature (correct me if I'm wrong) and wouldn't work with python 2.6, which impyla supports.

**Comment by xch91** [comment]
Ouch, you are absolutely right, python 2.6 indeed doesn't support dict comprehension.

The suggested version looks good too! Thanks a lot

**Comment by xch91** [comment]
Ah my pull request is merged :)

Issue can be closed

**Comment by wesm** [comment]
It was actually broken (fixed in https://github.com/cloudera/impyla/commit/2e567814868d9c248e5223da450ba9b3afe192b4); my fault for not running the test suite.

**Comment by wesm** [comment]
Feel free to make follow up patches.

**Comment by xch91** [comment]
My fault not running the test after I copied from my local util file too ):
