### ISSUE TITLE
"No module named thrift_sasl" error

### ISSUE THREAD

**Issue by mdowell12** [cloudera/impyla#204]
Trying to use `impala.dbapi.connect`, I got this error:

`ImportError: No module named thrift_sasl`

I executed the function with the following options:
- host = xxx
- port = xxx
- user = xxx
- password = xxx
- database = xxx
- auth_mechanism = "PLAIN"

I fixed the issue with `pip install thrift_sasl`.  I figured you guys may want to include thrift_sasl in the install_requires option in `setup.py`.

**Comment by wesm** [comment]
Technically sasl and thrift_sasl are optional dependencies for SASL or Kerberos support in impyla; some users have had a hard time installing these packages (e.g. on Windows, but now there is puresasl so that may help).

**Comment by mdowell12** [comment]
Works for me.  I'll close the issue.
