### ISSUE TITLE
cursor.rowcount() returns -1 for Impala/Kudu

### ISSUE THREAD

**Issue by briantwalter** [cloudera/impyla#209]
This could be "works as designed" but when I insert with this library to a table stored in Kudu I get a (-1) result for a successful insert and I would expect (1) row affected.

Code:

import impala.dbapi
conn = impala.dbapi.connect(host="hostname", port=21050)
cursor = conn.cursor()
sql = "INSERT into kudu_testing VALUES (%s, %s)"
row = [ 12345, "spaceballs"]
cursor.execute((sql), (row))
print 'Number of rows affected on INSERT is ' + str(cursor.rowcount)

Output:
Number of rows affected on INSERT is -1

**Comment by wesm** [comment]
https://www.python.org/dev/peps/pep-0249/#rowcount

I am not sure this information is available from the HiveServer2 interface

**Comment by schaffino** [comment]
The number of rows inserted is returned as data if you fetch after the insert.

**Comment by Saluev** [comment]
It would be useful if `rowcount` was equal to 0 after operations which don't return rows (e.g. `DROP TABLE`).

**Comment by wesm** [comment]
Can someone submit a PR? I don't have a Kudu-Impala cluster available for testing

**Comment by leejianwei** [comment]
Do we have plan to add this feature. I also met "-1" is returned when insert or update data.

**Comment by moravic** [comment]
For DML statements like UPDATE or INSERT it would be useful if rowcount would return the number of rows affected. Is it something you plan to add?

**Comment by prasanna-sk** [comment]
After digging around I think I have found a way to get the impacted row counts. I tested the code and works fine for all the below scenarios. 
Would appreciate if someone can a look and possibly get the changes merged **(if everything works)**

I have attached the modified `hiveserver2.py`. Below are the details. If the code looks OK, I can create a pull request with the change. Please let me know. 

[hiveserver2.py.txt](https://github.com/cloudera/impyla/files/3050006/hiveserver2.py.txt)

**`@property name: rowcounts`**

`usage: cursor.rowcounts`

returns: `modfiedRows, errorRows`

**For Non-Kudu tables:** (only _modifiedRows_ is relevant. _errorrows_ will always be -1) 

The code will return below values for diff scenarios.

- Create command : `(rows_inserted_with_create_query, -1)`
- Insert command: `(rows_inserted, -1)`
- Truncate/Drop command: `(-1, -1)`

_Note: With Kudu, when inserting a duplicate primary key, the row is 'ignored'. This will be shows as errorRows (second value that is returned)._

**For Kudu tables:**

The code will return below values for diff scenarios.

- Create command: `(rows_inserted, error_rows_ignored)`
- Delete command: `(rows_deleted, 0)` 
- Insert command: `(rows_inserted, error_rows_ignored)` 
- Update command: `(rows_updated, 0)`  
- Upsert command:  `(rows_upserted, 0)` 

Upsert counts get a little tricky, as they replace already existing rows. So, an existing row that is replaced/updated counts as modified rows. In addition, a new row inserted also counts in the same count.

**Comment by timarmstrong** [comment]
@prasanna-sk it would be easier to review if you created a pull request. That lets us see the exact diff and so on. I assume this is the important part:

`    @property
    def rowcounts(self):
        # Work around to get the number of rows modified for Inserts/Update/Delte statements
        modifiedRows, errorRows = -1, -1
        if self._last_operation_active:
            logList = self.get_profile().split('\n')
            resultDict = {}
            subs = ['NumModifiedRows', 'NumRowErrors']
            resultSet = [s for s in logList if any(item in s for item in subs)]
            if resultSet:
                for items in resultSet:
                    key, value = items.split(':')
                    key, value = key.strip(), value.strip()
                    resultDict[key] = value

                modifiedRows = int(resultDict.get('NumModifiedRows', -1))
                errorRows = int(resultDict.get('NumRowErrors', -1))

        return (modifiedRows, errorRows)`

I have to admit that it's a creative way to solve the problem given the limitations of the current HS2 interface. It feels hacky for sure but I guess it's not likely to break.

@twmarshall has looked at this problem in the past so I'd like to get his thoughts.

**Comment by prasanna-sk** [comment]
@timarmstrong  [Pull Request](https://github.com/cloudera/impyla/pull/346) created.

**Comment by prasanna-sk** [comment]
@timarmstrong  @twmarshall Any luck with merging this piece? I don't have a local instance to run pytest. Let me know how I can help.

**Comment by timarmstrong** [comment]
@prasanna-sk merged it. The profile parsing is ugly so I initially wanted to figure out a cleaner way, but I don't think it's possible if we want to support older Impala versions.

**Comment by ssubhasis** [comment]
When i call cursor.rowcounts i get error as thriftpy2.thrift.TApplicationException: Invalid method name: 'GetRuntimeProfile'
