### ISSUE TITLE
thrift generate is requred for TFetchResultsReq

### ISSUE THREAD

**Issue by hikoz** [cloudera/impyla#219]
fetchType is not exists in current _thrift_gen.
you need to re-generate thrift files.

https://github.com/cloudera/impyla/commit/2397ef2ce4d4b07dbb358661489245fa51328d39#diff-d3d6c567895a72663f13e753e636d355R1025
https://github.com/cloudera/impyla/blob/master/impala/_thrift_gen/TCLIService/ttypes.py#L5762

```
  File "xx/site-packages/impyla-0.13.8-py2.7.egg/impala/hiveserver2.py", line 1033, in get_log
    fetchType=1)
TypeError: __init__() got an unexpected keyword argument 'fetchType'
```

**Comment by schaffino** [comment]
#220 Not tested with python3 but seems to work fine with python 2.
