### ISSUE TITLE
as_pandas(): bad typecasts:  resultant DF has FLOAT columns from INT SQL columns

### ISSUE THREAD

**Issue by johndavidmiller** [cloudera/impyla#226]
First, thank you for impyla - it's really great to do interactive analysis using Python in Jupyter Notebooks from a Impala CDH cluster backend!  Especially for our data scientists who are used to doing this with e.g., Postgres backend - the workflow is identical.

However, a bug:  the dataframe returned by as_pandas() has float columns whereas the source data from SQL is INT.  This forces us to cast them in pandas with df[col] = df[col].fillna(0).astype(int)

The Fix:  as_pandas() gets the column data types returned from SQL and sets the DataFrame columns to the appropriate types.

Thanks, again,
-- jdm

**Comment by wesm** [comment]
@johndavidmiller pandas does not support NULL values in integer columns, so if the result set has nulls, then pandas will cast to float and set NaNs in their place. You can address this directly in SQL queries by replacing nulls with 0 in SQL. see http://www.cloudera.com/documentation/enterprise/5-6-x/topics/impala_conditional_functions.html
