### ISSUE TITLE
No module named dbapi

### ISSUE THREAD

**Issue by wmorin** [cloudera/impyla#227]
Hello,

I'm trying to run a simple python script using impyla:
```
from impala.dbapi import connect
```

When I run it I have the following error:
```
Traceback (most recent call last):
  File "impala.py", line 1, in <module>
    from impala.dbapi import connect
  File "/Users/wmorin/src/hadoop-etl/impala.py", line 1, in <module>
    from impala.dbapi import connect
ImportError: No module named dbapi
```

I'm under max OSX El captain. I use python installed via homebrew. I'm in a virtualenv and when I run `pip list` I can see
```
bitarray (0.8.1)
impyla (0.13.8)
pip (9.0.1)
setuptools (28.8.0)
six (1.10.0)
thrift (0.9.3)
wheel (0.29.0)
```

Here are some info on my setup:

```
$ python -V
Python 2.7.12

 pip -V
pip 9.0.1 from /Users/.../venv/lib/python2.7/site-packages (python 2.7)
```

Could you please help me?

**Comment by wesm** [comment]
@wmorin the problem is that your `impala.py` file is conflicting with the `impala` package name. Try calling the file something else

**Comment by wmorin** [comment]
Thanks a lot @wesm!

**Comment by Pechi77** [comment]
Facing same issue, even though my script name is different, I tried with notebook

**Comment by CrystalRanita** [comment]
Facing same issue, too.
My file name is: test2.py
Ubuntu 16.04 server version

connect==0.1
impala==0.2
six==1.10.0
thrift==0.9.3

Python 2.7.12
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

Log:
Traceback (most recent call last):
  File "test2.py", line 4, in <module>
    from impala.dbapi import connect
ImportError: No module named dbapi

**Comment by dknupp** [comment]
@CrystalRanita -- your list of installed libraries looks suspicious. I'm not sure what impala==0.2 is. Where did that come from?

When I install the latest of version of impyla (0.16.2), my environment looks like this.
```
$ pip freeze
bitarray==1.2.1
impyla==0.16.2
six==1.14.0
thrift==0.13.0
```

**Comment by CrystalRanita** [comment]
@dknupp Thanks for your help.
impyla==0.16.2 works. :)

**Comment by bambooheng** [comment]
pip install impyla==0.16.2 will ok
