### ISSUE TITLE
ImportError: libsasl2.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ha62791** [cloudera/impyla#237]
```
  File "/tmp/python/fwk_appln/py_demo_impyla/miniconda3/lib/python3.5/site-packages/impala/_thrift_api.py", line 151, in get_transport
    import sasl  # pylint: disable=import-error
  File "/tmp/python/fwk_appln/py_demo_impyla/miniconda3/lib/python3.5/site-packages/sasl/__init__.py", line 15, in <module>
    from sasl.saslwrapper import *
ImportError: libsasl2.so.2: cannot open shared object file: No such file or directory
```

No problem on CDH 5.8 (quickstart VM), the link libsasl2.so.2 is in /usr/lib64
```
[cloudera@quickstart bin]$ ls -lh /usr/lib64/libsasl*
lrwxrwxrwx. 1 root root   18 Aug 11 03:54 /usr/lib64/libsasl2.so.2 -> libsasl2.so.2.0.23
-rwxr-xr-x  1 root root 107K Mar 25  2015 /usr/lib64/libsasl2.so.2.0.23
```
but on CDH 5.9, the link is renamed to libsasl2.so.**"3"**
```
lrwxrwxrwx. 1 root root   17 Mar 20  2016 /usr/lib64/libsasl2.so.3 -> libsasl2.so.3.0.0
-rwxr-xr-x. 1 root root 119K Nov 21  2015 /usr/lib64/libsasl2.so.3.0.0
```

I am using:
- CDH 5.9
- Anaconda Python 3.5
- impyla 0.14.0
- bitarray 0.8.1
- thriftpy 0.3.9
- six 1.10.0
- sasl 0.2.1
- thrift-sasl 0.2.1
  
Pls try import the new libsasl2 when the old one is not found.

**Comment by ha62791** [comment]
The import of libsasl2.so.2 seems to be from within
`from sasl.saslwrapper import *`

I've create another issue for _**sasl**_
https://github.com/cloudera/python-sasl/issues/9

**Comment by ha62791** [comment]
The problem is due to in CDH5.9 it is CentOS 7, but in CDH 5.8 it is 6.7.
I solved the problem by reinstalling the **_'sasl'_** library in a CentOS 7 VM before uploading the whole python environment to the CDH cluster:
`sudo yum install cyrus-sasl-devel` (required for compiling during pip install)
`cd <miniconda home>/bin`
`./pip install impyla==0.14.0`
`./pip install thrift_sasl==0.2.1` (It will install the dependent **sasl 0.2.1**)

The compiled **sasl** python module will then import the new libsasl2 instead of the old one.

**Comment by jasonTangxd** [comment]
perfect
