### ISSUE TITLE
sql parameters formatting bug

### ISSUE THREAD

**Issue by timfeirg** [cloudera/impyla#263]
#### version 
impyla 0.14.0

#### problem
 string literals that contains `:\d` gets converted to something else, for example if I run this sql using impyla: 

```sql
select '2017-04-28 12:00:41'
```

the formatted sql would be:
```sql
select '2017-04-28 12:0050209621'
```

and so I found out there's [this line](https://github.com/cloudera/impyla/blob/master/impala/interface.py#L221) that assumes all `:\d`s are placeholders for sql arguments, can I send a patch to remove this behavior? and use the standard `%` operator for argument formatting? @wesm

**Comment by rafaelreuber** [comment]
This is Ok on impyla 0.16.2

```python
    from impala.dbapi import connect
    conn = connect(host='localhost', port=21050)
    cursor = conn.cursor()
    cursor.execute("select '2017-04-28 12:00:41'")
    print(cursor.fetchall()[0][0])
```
