### ISSUE TITLE
use python connect to hive from remote windows client, then error is coming:  No protocol version header.thriftpy.protocol.exc.TProtocolException: TProtocolException(type=4)

### ISSUE THREAD

**Issue by duniang818** [cloudera/impyla#270]
I want to access hiveserver2 use python3.6.3 and newest version impyla client from a windows machine.
But I met the error, when run the code cursor = conn.cursor():
No protocol version header.thriftpy.protocol.exc.TProtocolException: TProtocolException(type=4).

**Comment by BUNNYANIL** [comment]
Iam also getting same error can you help me on this as soon as possible

**Comment by 1450031369** [comment]
https://github.com/cloudera/impyla/issues/267#issuecomment-334389532 ; and you shoud change port=10000   to port =21050  ,now everthing goes well

**Comment by 092113219** [comment]
Do you use QQ, we chat together, I also meet this problem

**Comment by rafaelreuber** [comment]
> 21050

Thank you, this solved my problem.

**Comment by rafaelreuber** [comment]
I think this issue could be closed.

**Comment by timarmstrong** [comment]
I think this issue may be caused by a mix of different issues. I don't think we know how to reproduce the original issue.

**Comment by nanxiuzi** [comment]
> impcur = connect(host="kudu3", port=21050, database="yingda_test", password=None, user='admin', use_http_transport=True ).cursor()
> 
> I still got the error: `Traceback (most recent call last): File "/Users/edy/src/PythonProjects/dt-center-algorithm/test/1.py", line 4, in <module> impcur = connect(host="kudu3", port=21050, database="yingda_test", password=None, user='admin', use_http_transport=True ).cursor() File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/impala/hiveserver2.py", line 129, in cursor session = self.service.open_session(user, configuration) File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/impala/hiveserver2.py", line 1187, in open_session resp = self._rpc('OpenSession', req, True) File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/impala/hiveserver2.py", line 1080, in _rpc response = self._execute(func_name, request, retry_on_http_error) File "/usr/local/conda3/envs/py37/lib/python3.7/site-packages/impala/hiveserver2.py", line 1142, in _execute .format(self.retries)) impala.error.HiveServer2Error: Failed after retrying 3 times`

how to solve it?
