### ISSUE TITLE
hi, do the impyla package support on the windows platform? but i try many times, it din't access to hiveserver2.

### ISSUE THREAD

**Issue by duniang818** [cloudera/impyla#271]
hi, @toddlipcon:

There is my problem, and i have  no idea to solve it now, so I have to get help from you, I will very appreciat you.
 
I want to use python3.6.3 and impyla to access remotly hiveserver2 on linux server from a windows client, althought the demo is simple, but it doesn't work for me, and error is about binary protocol——no protocol header, how to handle it?

plz help me, it is very argent. Do you test on windows platform?
#270

**Comment by egormartiniuc** [comment]
Hi there I using Windows and its works fine. In your case I suppose issue related with sasl protocol unfortunately sasl on windows doesn't work well is used a fork from pyresasl.

**Comment by igorivanov** [comment]
Hi. Impyla works correct on Windows with different authorization mechanism - we have a different cases. Can you post full error text?
