### ISSUE TITLE
Not compatible with PyHive in Python 3 due to dynamic modify TCLIService 

### ISSUE THREAD

**Issue by guyskk** [cloudera/impyla#277]
Package versions:
```
impyla==0.14.0
thrift==0.10.0
thrift-sasl==0.3.0
thriftpy==0.3.9
sasl==0.2.1
PyHive==0.5.0
```

Reproduce steps:
```python
Python 3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import impala.dbapi
>>> import pyhive.hive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guyskk/ym/waimaietl/.venv/lib/python3.6/site-packages/pyhive/hive.py", line 11, in <module>
    from TCLIService import constants
ImportError: cannot import name 'constants'
>>> 
```

It was caused by https://github.com/cloudera/impyla/blob/master/impala/_thrift_api.py#L80, 
```
# dynamically load the HS2 modules
ExecStats = load(os.path.join(thrift_dir, 'ExecStats.thrift'),
                     include_dirs=[thrift_dir])
TCLIService = load(os.path.join(thrift_dir, 'TCLIService.thrift'),
                       include_dirs=[thrift_dir])
ImpalaService = load(os.path.join(thrift_dir, 'ImpalaService.thrift'),
                         include_dirs=[thrift_dir])
sys.modules[ExecStats.__name__] = ExecStats
sys.modules[TCLIService.__name__] = TCLIService   # <-----here!!!
sys.modules[ImpalaService.__name__] = ImpalaService
```

And PyHive also includes a TCLIService module, they conflict.

**Comment by brentonmallen1** [comment]
Is there a workaround for this?

**Comment by guyskk** [comment]
@brentonmallen1 swap the import order.

**Comment by brentonmallen1** [comment]
That worked, thanks!

**Comment by brentonmallen1** [comment]
even after reordering the imports, the error still pops up when running pytest.  I'm not sure if/how it's importing differently.  Have you experienced this?

**Comment by arjunsubway** [comment]
I am experiencing the same exact issue. I'm trying to connect to a Spark Thrift Server via Pyhive in an application that requires Impyla, and I'm receiving this error. @guyskk, were you able to find a solution to this problem? I don't have the option of switching the import order.

**Comment by celestewang1026** [comment]
Is there any method can solve this question

**Comment by Pillowman42** [comment]
I have the same issue, and it is occurring in a larger package so it is not a simple issue of reordering imports as the packages are imported at different points in different files.

Any fix to this?

**Comment by timarmstrong** [comment]
Yeah we probably should vendor the impyla thrift classes in a namespace, it's not generally valid to assume that different packages are even going to be using the exact same version of the thrift files

**Comment by potiuk** [comment]
Any chance for a release containing this fix @timarmstrong ? We have a problem in Apache Airflow that prevents us from merging https://github.com/apache/airflow/pull/8918 because of the very problem described here :(
