### ISSUE TITLE
connection.cursor () throws exception in Python 2

### ISSUE THREAD

**Issue by ajanac** [cloudera/impyla#286]
I used the below connection argument and when it worked fine. But when I did the connect.cursor() it throws the exception
connection = connect(
    host="xxxxx",  
    port=21050,
    auth_mechanism='GSSAPI',
    kerberos_service_name="impala"
)  # worked fine

cursorOne=connection.cursor() # throw error

Error Message:
/Users/ajanasathian/anaconda2/lib/python2.7/site-packages/impala/_thrift_gen/TCLIService/TCLIService.pyc in write(self, oprot)
   1067   def write(self, oprot):
   1068     if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
-> 1069       oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
   1070       return
   1071     oprot.writeStructBegin('OpenSession_args')

TypeError: expecting list of size 2 for struct args

It worked fine in Python 3.

**Comment by kkevinyang** [comment]
+1 
i have the same problem

**Comment by kkevinyang** [comment]
i solve this probem by `pip install thrift==0.9.3`

**Comment by ajanac** [comment]
Thanks, It worked! Appreciate it.

**Comment by Tagar** [comment]
Cloudera released `thrift_sasl` version `0.4.0a1`

https://pypi.org/project/thrift-sasl/0.4a1/#files
