### ISSUE TITLE
cursor.get_log() is not giving logs for hive - tez engine

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [cloudera/impyla#288]
We are using cursor.get_log() to check the status (% of map/reduce completion) of hive queries. If the execution engine is MR, we are able to get status from the logs. 

For tez engine the logs are not available. Is there any other API we can use to get `%` status of queries?

```
sql = 'set hive.execution.engine=tez'
cursor.execute_async(sql)
cursor.execute_async('select count(*), vendorid from db.newyork_taxi_data group by vendorid')
cursor.get_log()
```

**Comment by timarmstrong** [comment]
I think this is an issue with Hive. Impyla is just using the GetLog API provided by Hive.
