### ISSUE TITLE
Impyla and Python UDFs

### ISSUE THREAD

**Issue by DonDebonair** [cloudera/impyla#29]
I'm very eager to try out Python UDFs on Impala. I just don't really know how to get going. A couple of questions to make stuff more clear:
- I saw this merge commit: https://github.com/cloudera/impyla/commit/157ef1ed61a9bbf0b983364dbf624e1fdf601d14 Am I correct that the Python UDF code now lives in the master branch?
- In the `udf` package I see imports like this:

```
import llvm.core as lc
from numba import sigutils
from numba.compiler import compile_extra, Flags
```

When I look at the [setup.py](https://github.com/cloudera/impyla/blob/master/setup.py), I don't see any extra packages that are to be installed however. Should I install _numba_ (and any other packages) manually for udfs to work?

Maybe the README should be updated with some instructions for trying out Python UDFs :)

**Comment by statmatt** [comment]
All - any updates here? Would love to see a successful step-by-step procedure ...
