### ISSUE TITLE
about rowcount=-1

### ISSUE THREAD

**Issue by yangql881012** [cloudera/impyla#302]
when I get cur.rowcount property , It always return -1 ,How can I use it then I can get the actually afftected rows ,thank you

**Comment by prasanna-sk** [comment]
It is not implemented in Impyla afaik.

**Comment by csringhofer** [comment]
Bumped into this issue recently.

Create an Impala Jira about the problem:
https://issues.apache.org/jira/browse/IMPALA-12647

It has details about the possible ways to solve this. It is not straightforward though as Impala and Hive created incompatible solutions for this.

**Comment by csringhofer** [comment]
https://github.com/cloudera/impyla/pull/528 added support for rowcount
Note that rowcount in DML statements will only work with Impala (e.g it will be -1 in Hive)
