### ISSUE TITLE
Python to hive connection

### ISSUE THREAD

**Issue by srinu989** [cloudera/impyla#305]
We are trying to connect hive tables from python ,while connecting facing issues.We are sending our full details please help on this.
  we installed python version 2.7.15 and anaconda version 2.7.14
We installed below packages

pip install sasl
pip install thrift
pip install thrift-sasl
pip install PyHive

we written the below code to connect hive tables from python script

from pyhive import hive
conn = hive.Connection(host="172.16.17.196", port=10000, username="mapr", database="default")
cursor = conn.cursor()
cursor.execute("SHOW DATABASES")
for result in cursor.fetchall():
use_result(result)

We are getting below error

==========================

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\mapr\Anaconda2\lib\site-packages\pyhive\hive.py", line 64, in connect
return Connection(*args, **kwargs)
File "C:\Users\mapr\Anaconda2\lib\site-packages\pyhive\hive.py", line 162, in __init__
self._transport.open()
File "C:\Users\mapr\Anaconda2\lib\site-packages\thrift_sasl\__init__.py", line 79, in open
message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: Unable to find a callback: 2

**Comment by maxhardt** [comment]
Issues seems to be related to PyHive, not to impyla. Suggesting to close or move this issue.

**Comment by csringhofer** [comment]
Closing this as pyhive issue.

**Comment by punwatkaravi** [comment]
i am a cloudera user how can i do for python to hive connection
