### ISSUE TITLE
The future of impyla

### ISSUE THREAD

**Issue by ddonetskov** [cloudera/impyla#311]
Hello,

Could someone please clarify what the future of impyla is? 

At the moment, it looks like the project is not being developed any longer, however, I find it to be very useful for the community given it seems to be the only one which can provide the SQL interface to Impala in Python (without installing JDBC/ODBC). I understand there is the Ibis project but it does not allow working with SQL so it is not for SQL'ish person like myself.

Regards,
Dmitry

**Comment by timarmstrong** [comment]
We're continuing to develop it and have done some releases recently.
