### ISSUE TITLE
Parameter substitution issue 

### ISSUE THREAD

**Issue by msafiullah** [cloudera/impyla#317]
foo = "one" 
bar = "this is a string :1"
cursor.execute("insert into table 1 values(%s, %s)", [foo, bar])

:1 in string gets substituted with "one".

**Comment by jsrpy** [comment]
I had exactly the same problem today!

**Comment by msafiullah** [comment]
I used a work around for this. Don't use impyla execute method's parameter substitution. Use python's format method to substitute parameters. And write your own method to parameterize the parameter values.

**Comment by msafiullah** [comment]
```
import six
from impala.util import _escape

def parameterize (value):
	if value is None:
		return "NULL"
	elif isinstance(value, six.string_types):
		return "'" + _escape(value) + "'"
	else:
		return str(value)

```

**Comment by jsrpy** [comment]
Thanks for the workaround.

I'm still trying to get two values with colon into the right field.

Now I have

{page_url: "http://123.234.345.456:30001/",
 log_time: datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

I use your `parameterize` to wrap around these two values but in the table they sticks together into the `log_time` field like this:

```
| page_url                                                          | log_time            |
+-------------------------------------------------------------------+---------------------+
| http://123.234.345.4562018-12-14 16:313'                          | NULL                |
```

**Comment by timarmstrong** [comment]
#348  provided a workaround by allowing specification of a particular parameter style
