### ISSUE TITLE
Connection failed every few weeks

### ISSUE THREAD

**Issue by jsrpy** [cloudera/impyla#324]
I experience this error every 2-4 weeks:

`Failed after retrying 3 times`

The error usually comes in after date changes, at midnight 12AM after a few successful write in, then it starts to fail.

After that I kill the gunicorn process and restart it, and it works.

Wondering what is the cause of such error? The connection timeouts at a regular instance?

Below is my connection details:
`
conn = connect(host='datanode2', port=21050,
               user='user', database='db')
`

```
Python 3.6.4

impyla==0.14.1
```

**Comment by timarmstrong** [comment]
You could see symptoms like this if the connection uses kerberos and the ticket expires.

I'm going to close since we can't reproduce this.

**Comment by timarmstrong** [comment]
You could see symptoms like this if the connection uses kerberos and the ticket expires.

I'm going to close since we can't reproduce this.
