### ISSUE TITLE
Update README to import process

### ISSUE THREAD

**Issue by KarinaMarks** [cloudera/impyla#351]
I'm new to this package and was attempting some of the examples in the README, and am finding myself very confused. Not sure if it's the code or the explanation.

Lines 107 - 111 have the following;
```python
cursor.execute('SELECT * FROM mytable LIMIT 100')
for row in cursor:
    process(row)
```
But the `process` function is not imported anywhere. 

Is this an actual function? - If so where is it from / what does it do? 

Or, is this psuedo for 'do some process'? - If so it would be good to explain this in the wording around the code chunk just for those new to the package who spend a while looking for the `process` function: "The `Cursor` object also exposes the iterator interface, which is buffered
(controlled by `cursor.arraysize`), so any 'process' type function can be used on the values:"

Apologies if this is really simplistic and obvious to you - but I got confused while looking at it, so thought it would be good to let you know!

Thanks

**Comment by timarmstrong** [comment]
@KarinaMarks I believe you're right that it's just a placeholder for "do some processing". Thanks for the feedback, I think we should improve it - no reason for documentation to be cryptic when it doesn't need to be. I'm sure others have been confused and just not bothered to provide feedback. 

Please feel free to submit a PR with improved wording or we can take a look ourselves.
