### ISSUE TITLE
return code 1 org.apache.hadoop.hive.ql.exec.spark.SparkTask

### ISSUE THREAD

**Issue by wenhuiwwh** [cloudera/impyla#358]
The following question has be meeted for me by using impyla connect to hive 
`
impala.error.OperationError: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.spark.SparkTask
`

**Comment by timarmstrong** [comment]
That is an error produced by hive. It is unrelated to the Impyla driver.
