### ISSUE TITLE
Issue catalog exception

### ISSUE THREAD

**Issue by LucaNicoliYT88** [cloudera/impyla#383]
Hi, when I am triyng to make a query, I have got the following error:

CatalogException: Table 'xindustry.x_industry_iot' was modified while operation was in progress, aborting execution.

the code sounds like this:

table_name = 'x_industry_iot'
schema_name = 'xindustry'

conn = connect(host=host_v, port=port_v)
Cur = conn.cursor()

query = f"""SELECT * FROM {schema_name}.{table_name} 
WHERE {table_name}.thing_id = "X" and {table_name}.tag_trendid = "X" and 
month = "M" and year ="Y" and day = "D" """

Cur.execute(query)
data = as_pandas(Cur)
conn.close()

My version of library is 0.15.0

**Comment by timarmstrong** [comment]
This error is returned by the Impala service itself under some scenarios. This isn't related to the Impyla client.

There is most likely some other operation modifying the table object, e.g. an "alter table", "compute stats" or other operation. I'd suggest emailing user@impala.apache.org or asking on https://community.cloudera.com/ to get input on how to avoid it. Please include the Impala version and as many details about the workload as possible.
