### ISSUE TITLE
happybase connection

### ISSUE THREAD

**Issue by aalgosaibi** [cloudera/impyla#387]
Hi
I'm trying to connect to happybase and following the steps of this website: https://happybase.readthedocs.io/en/latest/user.html
This is my code:
`import happybase
connection = happybase.Connection(host='localhost', port=9090, timeout=None, autoconnect=True)

connection.open()`
I'm able to import it, but when I try, to connect. I get this error: 

`---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
/opt/anaconda3/lib/python3.7/site-packages/thriftpy2/transport/socket.py in open(self)
     95 
---> 96             self.sock.connect(addr)
     97 

ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

TTransportException                       Traceback (most recent call last)
<ipython-input-32-650cfd145ae6> in <module>
      1 import happybase
      2 connection = happybase.Connection(host='localhost', port=9090, timeout=None, autoconnect=True, table_prefix=None, table_prefix_separator=b'_', 
----> 3                                   compat='0.98', transport='buffered', protocol='binary')
      4 
      5 

/opt/anaconda3/lib/python3.7/site-packages/happybase/connection.py in __init__(self, host, port, timeout, autoconnect, table_prefix, table_prefix_separator, compat, transport, protocol)
    146 
    147         if autoconnect:
--> 148             self.open()
    149 
    150         self._initialized = True

/opt/anaconda3/lib/python3.7/site-packages/happybase/connection.py in open(self)
    174 
    175         logger.debug("Opening Thrift transport to %s:%d", self.host, self.port)
--> 176         self.transport.open()
    177 
    178     def close(self):

/opt/anaconda3/lib/python3.7/site-packages/thriftpy2/transport/buffered/cybuffered.pyx in thriftpy2.transport.buffered.cybuffered.TCyBufferedTransport.open()

/opt/anaconda3/lib/python3.7/site-packages/thriftpy2/transport/socket.py in open(self)
    103             raise TTransportException(
    104                 type=TTransportException.NOT_OPEN,
--> 105                 message="Could not connect to %s" % str(addr))
    106 
    107     def read(self, sz):

TTransportException: TTransportException(type=1, message="Could not connect to ('localhost', 9090)")`

**Comment by timarmstrong** [comment]
This is the bugtracker for impyla, not happybase.
