### ISSUE TITLE
Library Offline Installation

### ISSUE THREAD

**Issue by AbdelrahmanAli** [cloudera/impyla#395]
Hi, I wonder how can I install impyla on a server with no internet connection?

**Comment by timarmstrong** [comment]
You can do it the same way as you would install other pip packages offline - download the packages and all dependencies, get them on the server, then run pip install, pointing at the downloaded packages.

Once you figure out the packages you need you can do the downloading and installation separately something like this:
`
pip download --dest <dir> <package 1> <package 2>

pip install --find-links <dir> <package 1> <package 2>
`

If you're operating at a larger scale you can also run a pip mirror (I can't help you with that).

**Comment by AbdelrahmanAli** [comment]
So, my environment is a Redhat 7 Linux Server. 

I followed @timarmstrong advice and searched about how can I install packages offline using pip.
I found this [link](https://www.nyayapati.com/srao/2014/06/how-to-pip-install-python-packages-offline/). 

The guy explains that he download packages offline then used this command 
`pip install --no-index --find-links=file:/$HOME/.mypypi ipython`  
to install the package.

He didn't explain where to get those packages though, so I thought about installing `bit_array` as I remember when I checked the Python packages installed on the server using this command `pydoc modules` I didn't see `bit_array` and its one of the dependencies of impyla.

I went to this [link](https://pypi.org/project/bit_array/#files) and downloaded **bit_array-0.1.0.tar.gz** 
I noticed this command
![image](https://user-images.githubusercontent.com/9371556/79392587-434ccb80-7f7c-11ea-9012-2eee6c3c642a.png)
and I guessed that I should use `bit_array` in the offline pip install command like this
`pip install --no-index --find-links=file:/$HOME/.mypypi bit_array` 
I put the downloaded **bit_array-0.1.0.tar.gz**  in **/home/bdadmin/mypypi** in the server and I run the command and it worked.

I checked the python packages again using `pydoc modules` and I found `bit_array` there.

Using the same process, I tried to offline pip install Impyla. So I downloaded it from this [link]([url](https://pypi.org/project/impyla/#files)) , I put it in **/home/bdadmin/mypypi**, I got the package name and I run the command
`sudo pip install --no-index --find-links=file:$HOME/mypypi impyla`

It said that I need to a new version of `setuptools` and I found it on this [link](https://pypi.org/project/setuptools/#files)
`sudo pip install --no-index --find-links=file:$HOME/mypypi setuptools`

After installing the `setuptools` I tried to install impyla again, but it failed cause of `bitarray` which I found on this [link](https://pypi.org/project/bitarray/#files)
`sudo pip install --no-index --find-links=file:$HOME/mypypi bitarray`

It failed cause there was no GCC compiler. I ignored that and tried to install Impyla again it passed the bitarray part and failed cause `thrift ` which I found on this [link](https://pypi.org/project/thrift/#files)
`sudo pip install --no-index --find-links=file:$HOME/mypypi thrift`
then I tried impyla again, it passed, but it stop cause of gcc. 

I found this [link](https://www.cyberciti.biz/faq/centos-rhel-7-redhat-linux-install-gcc-compiler-development-tools/) which says, for Redhat 7, try to do `sudo yum group list`, if you find **Development Tools**, then you can run `sudo yum group install "Development Tools"` to install gcc
I did it and now I have gcc.

I tried to install Impyla again, but it failed, gcc couldn't run the command and it gave me the following error
> "bitarray/_bitarray.c:12:20: fatal error: Python.h: No such file or directory"

I googled it and found this [link](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory), The guy said to re-install python 
so I used this command
`sudo yum install python-devel   # for python2.x installs`
and it worked
I tried to install Impyla and it worked!

**Comment by timarmstrong** [comment]
In recent versions of pip, "pip download" is the easiest way to download things. Glad you got unblocked though!

**Comment by AbdelrahmanAli** [comment]
Thanks for your guidance ^^
