### ISSUE TITLE
Impyla does not respect TZ environment variable

### ISSUE THREAD

**Issue by anandnalya** [cloudera/impyla#426]
In python, a default timezone different from system timezone can be specified with `TZ` environment variable. [ImpalaService.thrift](https://github.com/cloudera/impyla/blob/v0.16.3/impala/thrift/ImpalaService.thrift#L333-L335) also says that the value provided for `TZ` can is used for `UTC<->localtime conversions` but this does not work. 

```python
$ TZ="UTC" python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from datetime import datetime
>>> import impala
>>> import impala.dbapi

>>> connection=impala.dbapi.connect(host='hive-server.ip', port=10000, auth_mechanism=None, user='test')
>>> cursor = connection.cursor()
>>> cursor.execute("select current_timestamp")
>>> cursor.fetchall()
[(datetime.datetime(2021, 1, 8, 6, 0, 35, 535000),)]

>>> datetime.now()
datetime.datetime(2021, 1, 8, 11, 0, 49, 565775)
```

The above snippet was run on on a system with timezone set to `America/New_York`. The timezone for the Hive server is also `America/New_York`. We can see that after setting `TZ=UTC`, `datetime.now()` returns a value in `UTC` time zone while the value returned by Hive is not converted `UTC` .

**Comment by timarmstrong** [comment]
ImpalaService.thrift is just the internal API docs, it doesn't apply to Impyla and isn't intended as user documentation.

The timezone is configured server-side anyway. Also that documentation is talking about Impala's behavior, not Hive's.

I don't know about Hive, but on Impala the server-side timezone can be overridden via the Impala query option TIMEZONE. There's probably an equivalent for hive but this isn't the place for that.
