### ISSUE TITLE
Does impala0.16.3 support "add file xxx"?

### ISSUE THREAD

**Issue by simpledong81** [cloudera/impyla#427]
When I run "cursor.execute('add file /home/hadoop/xxx.py')", it always returns "impala.error.HiveServer2Error: Error while processing statement: null".

hadoop               2.7.1
hive                     2.3.7
python                3.7
impyla                 0.16.3
protobuf               3.14.0
sasl                   0.2.1
thrift                 0.13.0
thrift-sasl            0.2.1
thriftpy2              0.4.12

**Comment by timarmstrong** [comment]
Impyla is the client library, it does not control what statements are supported on the server side.
