### ISSUE TITLE
_wrap_results takes three positional arguments but passing two arguments.

### ISSUE THREAD

**Issue by dhanababum** [cloudera/impyla#454]
When I implementing get_log in my project found an issue.
https://github.com/cloudera/impyla/blob/v0.17.0/impala/hiveserver2.py#L1345

_wrap_results takes three positional arguments but passing two arguments.

**Comment by dhanababum** [comment]
https://github.com/cloudera/impyla/pull/453

**Comment by attilajeges** [comment]
The PR was merged in.
