### ISSUE TITLE
Received bytes from impyla in JH

### ISSUE THREAD

**Issue by Vosec** [cloudera/impyla#455]
Hello,

I'm trying to receive data in JH from Impyla, everything works fine except one table is returning data in bytes - b''.
Code:

`from impala.dbapi import connect

conn = connect(host=host, port=21050, user={userName}, use_ssl=True, auth_mechanism='GSSAPI', kerberos_service_name='impala', database=db)
cursor = conn.cursor()
cursor.execute(sql)
data = cursor.fetchall()`

example output: 
b'', b'CZ', b'CZE', b'Hlavn\xc3\xad 51', 

it is happening only on 1 DB, other DBs and tables I have tested are ok in utf-8.

Packages:
impyla                    0.17.0                   pypi_0    pypi
bitarray                  2.1.0                    pypi_0    pypi
six                       1.14.0                     py_1    conda-forge
thrift                    0.11.0                   pypi_0    pypi
thrift-cpp                0.13.0               h62aa4f2_2    conda-forge
thrift-sasl               0.4.3                    pypi_0    pypi
thriftpy                  0.3.9           py37h516909a_1001    conda-forge
thriftpy2                 0.4.14           py37h5e8e339_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge

However, if I run same query not from JH, but directly from server the output is in correct encoding - no bytes.
Packages on server:
impyla                    0.16.3           py37hc8dfbb8_0    conda-forge
bitarray                  2.0.1            py37h5e8e339_0    conda-forge
thrift                    0.13.0           py37hcd2ae1e_2    conda-forge
thrift_sasl               0.4.2            py37h8f50634_0    conda-forge
thriftpy                  0.3.9           py37h516909a_1001    conda-forge
thriftpy2                 0.4.14           py37h5e8e339_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge

Any clues? :)
Thank you.

**Comment by attilajeges** [comment]
Hi,
what version of Python are you using (when querying from JH  and on the server)?  Also, what is the schema of the result set of your SQL query? 
If you are using impyla with python 3 and the column type is CHAR or VARCHAR then it is expected that you'll get bytes instead of a unicode string. If that is the case, please consider using STRING column type instead. Impyla will treat STRING values as utf-8 encoded unicode strings and return them as unicode strings.

**Comment by Vosec** [comment]
@attilajeges 
Hello,  
thank you for your answer. You are correct, it seems that if column is varchar, then I'm getting bytes, is there any way of changing this?

Another thing, I tried to downgrade impyla version in JH as it is on my server =  impyla 0.17.0 pypi_0 pypi ->  impyla 0.16.3
and Im getting utf-8 encoded string even on varchar columns. But, there is another issue with "invalid query handle".

With  impyla 0.17.0 Im able to get millions of rows, but with  impyla 0.16.3 I can get a really small amout, otherwise it will throw exception with Invalid query handle. - Any tips ?

Thank you

**Comment by attilajeges** [comment]
Hi, looks like the VARCHAR - bytes issue is a bug in Impyla 0.17.0 after all. Impyla should return unicode strings for VARCHAR columns as well. We will fix this issue and create a new release shortly. Until the new release is available, as a quick workaround you can convert the bytes values to unicode strings yourself: e.g.

data = cursor.fetchall()
for i, row in enumerate(data):
  data[i] = tuple(v.decode('utf-8') if isinstance(v, bytes) else v for v in row)

The 0.16.3 release had many issues so I wouldn't recommend downgrading impyla to 0.16.3.

**Comment by Vosec** [comment]
Hello,
thank you for your response. Ok, I understand. I have sorted out almost same way as your workaround, but I will use your code. It looks somewhat cooler :)

Thank you again! We may close this and I will look forward to the new release.
