### ISSUE TITLE
`ImpalaDialect.get_columns` incompatible with the latest SQLAlchemy 2.0 version

### ISSUE THREAD

**Issue by lazyhope** [cloudera/impyla#536]
With the new SQLAlchemy 2.0 version `ImpalaDialect.get_columns` is broken, since `connection.execute('plain_text')` is deprecated and should be replaced with `connection.execute(text('plain_text'))` where `text` is imported from `sqlalchemy`, so this line and any other `connection.execute` would fail: https://github.com/cloudera/impyla/blob/747e1da3d0df6abae9beb633cb9ebdd6f210ad30/impala/sqlalchemy.py#L264

**Comment by tomanizer** [comment]
fixed in [d6582ad](https://github.com/cloudera/impyla/commit/d6582ad907672cf98541c2af388b4d48eed99280)
