### ISSUE TITLE
Failed to import pandas message makes Pandas kind of required

### ISSUE THREAD

**Issue by DandyDev** [cloudera/impyla#58]
Impyla tries to import Pandas, and when it fails, [it will print](https://github.com/cloudera/impyla/blob/master/impala/util.py#L26-L27) "Failed to import pandas". I'm using Impyla as part of a command line tool, so this message will always pop up when Pandas is not installed, even though I have no need of the `as_pandas()` method, and thus don't want to force users to install Pandas.
If Impyla would make use of Python's logging facilities, I could at least "swallow" that message in my app by also configuring logging. Any ETA [on this](https://github.com/cloudera/impyla/issues/23)? 

Maybe even better would be to do the Pandas import _inside_ the `as_pandas()` method. Like this:
```python
def as_pandas(cursor):
    try:
        import pandas as pd
        names = [metadata[0] for metadata in cursor.description]
        return pd.DataFrame.from_records(cursor.fetchall(), columns=names)
    except ImportError:
        print "Failed to import pandas"
```

**Comment by kevinastone** [comment]
:+1:

**Comment by laserson** [comment]
Good suggestion for a quick fix, @DandyDev.  Multiple people have commented on the annoying message.  Let me know if there are still problems.
