### ISSUE TITLE
Try using C impl for Thrift code to speed things up

### ISSUE THREAD

**Issue by laserson** [cloudera/impyla#60]
Fetching rows from HS2 is dominated by time spent in the pure python Thrift code.  Will it be faster if we code gen C code and then wrap it?

**Comment by toddlipcon** [comment]
If I recall correctly there is also an "accelerated protocol" implementation in thrift python which can be faster than the stock TBinaryProtocol. Try that? Also make sure that you've got either a framed transport or a BufferedTransport to avoid a bajillion tiny read() syscalls

**Comment by laserson** [comment]
Thanks for the suggestions.  We switched to the `TBinaryProtocolAccelerated` some time ago, and always used the `TBufferedTransport`, but it's still pretty slow :(

**Comment by toddlipcon** [comment]
OK. Interesting idea to try wrapping the C code, then! I'll watch this issue

**Comment by mariusvniekerk** [comment]
The other thing this would give us is python 3 compatibility.  Which would be nice. 

 I haven't really seen anybody wrapping the cpp/c Thrift generated code would be very useful for other projects as well.

**Comment by laserson** [comment]
+1, great point!

**Comment by wesm** [comment]
this is superseded in parts by cloudera/hs2client and thriftpy
