### ISSUE TITLE
Query options passed in cursor.execute(configuration={dict of query options}) don't work

### ISSUE THREAD

**Issue by awleblang** [cloudera/impyla#61]
Say I'm trying to limit the memory or a query:
In [2]: conn = connect(host='localhost', port=21050)
In [3]: cur = conn.cursor()
In [4]: cur.execute("SELECT COUNT(*) FROM tpch.lineitem", configuration={"MEM_LIMIT":"1"})
In [5]: cur.fetchall()
Out[5]: [(6001215,)]

This should fail because I'm limiting the memory down to 1 byte. 

If I set the configuration at the cursor creation, it does fail as expected.
In [11]: limited_cur = conn.cursor(configuration={"MEM_LIMIT":"1"})
In [12]: limited_cur.execute("SELECT COUNT(*) FROM tpch.lineitem")
~~~error stuff here~~~
In [13]: limited_cur.fetchall()
~~~error stuff~~~
HiveServer2Error: Memory limit exceeded

**Comment by laserson** [comment]
Thanks for reporting this @awleblang.  You said you were working on a PR or should I take a crack at it?

**Comment by awleblang** [comment]
I haven't started working on a fix yet. I would greatly appreciate you taking a look at it.

**Comment by laserson** [comment]
Fixed, @awleblang.
