### ISSUE TITLE
from_pandas error 'HiveServer2Connection' object has no attribute '_temp_dir'

### ISSUE THREAD

**Issue by jbarotin** [cloudera/impyla#62]
Hello,

I'm trying to use impala.bdf.from_pandas function, I've got the following code :
```python
# -*- coding: utf8
import pandas as pd
from impala.dbapi import connect
from impala.bdf import from_pandas

if __name__ == '__main__':
    csv = pd.read_csv("mydata.csv")
    ci = connect(host="localhost",
                 port=21050)
    from_pandas(ci, csv, method='in_query')
```
I've got the following error message :
```Traceback (most recent call last):
  File "panda_df_impala_issue.py", line 13, in <module>
    from_pandas(ci, csv, method='in_query')
  File "/home/cloudera/Public/base_big_data/virtenv_py26/lib/python2.6/site-packages/impala/bdf.py", line 117, in from_pandas
    table = "%s.%s" % (ic._temp_db, temp_table)
AttributeError: 'HiveServer2Connection' object has no attribute '_temp_db'```

I tried to fill the table parameter of the from_pandas function, but a string doesn't fit. What is the type of this parameter ?

Any other idea to help me ?

**Comment by laserson** [comment]
Sorry for the trouble, @jbarotin.  What type of object are you passing into `from_pandas()` for the `ic` argument?  It's expecting an `ImpalaContext` but the error makes it look like you're passing a `HiveServer2Connection` (which is what `connect()` returns).

**Comment by jbarotin** [comment]
All right, but there are not all a lot of documentation about this object : "ImpalaContext".

It is mandatory to use webhdfs with it ?

**Comment by laserson** [comment]
Yes, sorry about that, the IC/BDF is basically completely undocumented.  It's on the todo list but it may be a while.

WebHDFS is not required, but to use `from_pandas`, you have to specify either `in_query` or `webhdfs` as the method to transport the data.  The former actually creates a DDL statement with the dataframe hardcoded into the SQL query as literals, which may be bad if you have a lot of data.  So while WebHDFS is not required, I anticipate it'll be better for larger data frames.

**Comment by mariusvniekerk** [comment]
As far  as I recall in the exit of the impala context it uses webhdfs to clean up the temporary dfs paths it made

**Comment by laserson** [comment]
That's right, though it's wrapped in a try/except block so it should just spit out an annoying error message and move on.

**Comment by mariusvniekerk** [comment]
Yeah it will move on, but it will leave the impala database it created behind.  

We may want to clean that up a bit.  I can take a look at that teardown if we want to.

**Comment by laserson** [comment]
It appears that if the directory backing the impala database did not exist prior to the `CREATE DATABASE` command, then the subsequent `DROP DATABASE` will delete the directory.

Either way, I am preparing a PR to deal with #65 that changes this logic a touch.  Check it out and let's open a new issue if we think it still needs more cleanup.
