### ISSUE TITLE
Kerberos support in HDFS client

### ISSUE THREAD

**Issue by schaffino** [cloudera/impyla#65]
I've just installed impyla on our cluster and have had success in using for query execution, however it seems its using the pywebhdfs module which doesn't support kerberised clusters, so any hdfs related functionality doesn't work.  Are there plans to move to a module that supports Kerberos auth? 
For instance, https://pypi.python.org/pypi/hdfs/0.5.0.

**Comment by sodre** [comment]
+1 for this feature.

**Comment by laserson** [comment]
Thanks for reporting this, @schaffino. Let me look into the hdfs package you point to. Any thoughts on this, @mariusvniekerk?

**Comment by mariusvniekerk** [comment]
If it's a drop in replacement then it should be pretty simple to switch to it.  I think the blaze guys use pywebhdfs.

**Comment by laserson** [comment]
@schaffino @sodre let me know if this fixes things for you.  I switched to the `hdfs` package and successfully ran the test suite against a kerberized cluster.  Note you need the latest release of the `hdfs` package.

**Comment by schaffino** [comment]
I've tested the client calls manually but I'm getting a number of other errors. I think it might be because the test suite does not allow using a kerberized impala cluster.

**Comment by laserson** [comment]
i'll confess that i have not yet set up the CI for a kerberized cluster, but I'd guess the only thing you should need is `export USE_KERBEROS=True` and make sure to `kinit`.
