### ISSUE TITLE
Compile Impala types when creating SQLAlchemy table

### ISSUE THREAD

**Issue by bhtucker** [cloudera/impyla#71]
After some encouragement from @mrocklin at PyCon, gave Impyla SQLAlchemy a try.
It seems the Impala types may not be registered with the SQLAlchemy type compiler.

Simple demo:
```{python}
from impala.sqlalchemy import STRING, INT, FLOAT, TIMESTAMP
from sqlalchemy import Table, Column
from sqlalchemy.schema import MetaData

engine = sqlalchemy.engine.create_engine('impala://localhost')

metadata = MetaData(engine)

mytable = Table("mytable", metadata,
      Column('mytable_id', sqlalchemy.INT),
      Column('value', STRING)
)
mytable.create()

CompileError: (in table 'mytable', column 'value'): Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x1080d1810> can't render element of type <class 'impala.sqlalchemy.STRING'>
```

**Comment by laserson** [comment]
Thanks for reporting this, @bhtucker.  I have very minimal SQLAlchemy knowledge, and essentially stole the minimal amount of code from PyHive that would make some examples run.  Is this an easy fix?  And is it blocking you at the moment?

**Comment by laserson** [comment]
This reproduces without needing an Impala connection:

```python
import sqlalchemy.engine
from impala.sqlalchemy import STRING, INT, FLOAT, TIMESTAMP
from sqlalchemy import Table, Column
from sqlalchemy.schema import MetaData, CreateTable

engine = sqlalchemy.engine.create_engine('impala://localhost')

metadata = MetaData(engine)

mytable = Table("mytable", metadata,
      Column('mytable_id', sqlalchemy.INT),
      Column('value', STRING)
)

print CreateTable(mytable)
```

**Comment by laserson** [comment]
@bhtucker let me know if this commit fixes things for you

**Comment by bhtucker** [comment]
will give it a try, thanks!

In my own debugging, I also arrived at those missing visit methods as the culprit. Is there any documentation/similar code that pointed you towards this fix?

**Comment by bhtucker** [comment]
Running your snippet above, I still hit the same error.

A bit of PDB-ing shows that the CreateTable object doesn't have the dialect set:
```
(Pdb) self
<sqlalchemy.sql.ddl.CreateTable object at 0x10e2b4b90>
(Pdb) self.dialect
```
Which leads the DDL element to be set to the DefaultDialect:
```
-> if not dialect:
(Pdb) dialect
(Pdb) n
...
-> dialect = default.DefaultDialect()
(Pdb) default.DefaultDialect()
<sqlalchemy.engine.default.DefaultDialect object at 0x10e3adcd0>
```

This DefaultDialect uses the GenericTypeCompiler, which of course doesn't have the visit methods you added yesterday:
```
(Pdb) dialect.type_compiler
<class 'sqlalchemy.sql.compiler.GenericTypeCompiler'>
```

So I still get:
```
CompileError: (in table 'mytable', column 'col1'): Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x10e3bae10> can't render element of type <class 'impala.sqlalchemy.STRING'>
```

Did your commit make your last snippet run successfully?

Appreciate your looking into this, hope my debugging is at least slightly helpful.

**Comment by laserson** [comment]
Ah, sorry.  You need to give a `bind=engine` arg to the fn as well.  This will ensure it gets the right dialect.  See the test that I added to impyla.

**Comment by bhtucker** [comment]
Yep seems like we're good now! Thanks!
