### ISSUE TITLE
UDF - where is numba.ext.impala?

### ISSUE THREAD

**Issue by cgc17** [cloudera/impyla#72]
I am probably missing something obvious here, so bear with me...

I have installed and am currently using impyla to connect to and query impala. I have also installed the dependencies for UDFs (including numba, llvm, llvmpy, boost), but importing `numba.ext.impala` does not work.  Where do I need to get this?

**Comment by laserson** [comment]
Note that the UDF stuff has only been tested with `numba<=0.13.4`, and I'd suggest using that specific version.  It will definitely fail with the latest version of numba.

Otherwise, no need for `numba.ext.impala`, and it actually no longer exists.  You should use `impala.udf.xxx`.

**Comment by cgc17** [comment]
@laserson yep, I've got 0.13.4.  Thanks for the quick response!
