### ISSUE TITLE
Update run-dbapi.sh to use released python-sasl

### ISSUE THREAD

**Issue by laserson** [cloudera/impyla#79]
Currently, the Jenkins test script uses laserson/python-sasl@cython to run the tests, because the branch has not yet been merged.  This should be updated once a new python-sasl is released.

**Comment by laserson** [comment]
Blocked on merging toddlipcon/python-sasl#8

**Comment by Raynes** [comment]
Looking at the PR, it's hard to figure out what is currently blocking. It appears there was an agreement for someone to take over maintenance of python-sasl and there is a [cloudera/python-sasl](https://github.com/cloudera/python-sasl) repository, but nothing else has happened.

Is development expected to move forward on the Cloudera repository?

**Comment by laserson** [comment]
Yes. @wesm is going to take over maintenance and hopefully review/merge the patch soon.

**Comment by wesm** [comment]
this is all set now
