### ISSUE TITLE
Evaluate feasibility of supporting python 2.5

### ISSUE THREAD

**Issue by laserson** [cloudera/impyla#81]

**Comment by mariusvniekerk** [comment]
Just out of curiosity what still uses 2.5?

I can understand trying for 2.6 since it is the default python on Ubuntu 14.04

**Comment by jwills** [comment]
I figured @laserson was just showing off now. ;-)

**Comment by laserson** [comment]
Ha!  @mariusvniekerk, the Impala team is trying to consolidate the Python code to access HS2.  We have clients that still need Python 2.5 (CentOS5 perhaps?), and possibly even Python 2.4 (though I don't think I'm gonna bother with that)

**Comment by wesm** [comment]
I think Python < 2.6 support at this point is out
