### ISSUE TITLE
Is there merit in considering invalidate metadata automatically

### ISSUE THREAD

**Issue by srjgit** [cloudera/impyla#98]
Hi ,

Wondering if there's merit in issuing "invalidate metadata" as part of connect() i.e when I receive a connection object it should by default have latest metadata sync'ed up automatically?

thanks
Sreejith

**Comment by laserson** [comment]
I'm guessing this is not ideal.  My understanding is that invalidate metadata could be expensive at times, and I'd rather not have impyla implicitly executing queries on the user's behalf.  To my knowledge, this happens only in the case when a user specifies a `default_db`.

**Comment by srjgit** [comment]
Thanks for the response. I understand this falls on the borderline of driver responsibility vs application's. Perhaps one other option could be to support a flag - am drawing parallel to Connect attributes supported by DBI/DBD perl modules for instance. Also, from application developer's perspective I'd almost always want to begin with my metadata in sync as default behavior. Just my 2cents

**Comment by laserson** [comment]
I believe you can run your impalad with something like `sync_ddl=True`, which should have the same effect.

**Comment by srjgit** [comment]
Thanks, Will explore this option. We can close this issue now
